CREATE TABLE [dbo].[bipedestacion] (
    [idBipedestacion]            UNIQUEIDENTIFIER NOT NULL,
    [visionAnterior]             NVARCHAR (MAX)   NULL,
    [visionPosterior]            NVARCHAR (MAX)   NULL,
    [visionLateral]              NVARCHAR (MAX)   NULL,
    [basculaEscapular]           BIT              NOT NULL,
    [basculaPelvica]             BIT              NOT NULL,
    [balculaPelvicaMM]           FLOAT (53)       NULL,
    [posicionEscoliotica]        BIT              NOT NULL,
    [testAdams]                  BIT              NOT NULL,
    [testAdamsGiro]              NVARCHAR (MAX)   NULL,
    [pruebaIsquiotibilaesCortos] BIT              NOT NULL,
    [genuFisiologico]            BIT              NOT NULL,
    [genuValgo]                  BIT              NOT NULL,
    [genuValgoDim]               FLOAT (53)       NULL,
    [genuVaro]                   BIT              NOT NULL,
    [genuVaroDic]                FLOAT (53)       NULL,
    [tibiasFisiologicas]         BIT              NOT NULL,
    [tibiasValgas]               BIT              NOT NULL,
    [tibiasVaras]                BIT              NOT NULL,
    [pieRadioInsuficiente]       BIT              NOT NULL,
    [pieRadioInsucienteNotas]    NVARCHAR (MAX)   NULL,
    [pieSobrecargaMeta]          BIT              NOT NULL,
    [pieSobrecargaMetaNotas]     NVARCHAR (MAX)   NULL,
    [id_retropie]                UNIQUEIDENTIFIER NULL,
    [id_antepie]                 UNIQUEIDENTIFIER NULL,
    [id_fpi]                     UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_bipedestacion] PRIMARY KEY CLUSTERED ([idBipedestacion] ASC),
    CONSTRAINT [FK_bipedestacion_antepie] FOREIGN KEY ([id_antepie]) REFERENCES [dbo].[antepie] ([idAntepie]),
    CONSTRAINT [FK_bipedestacion_FPI] FOREIGN KEY ([id_fpi]) REFERENCES [dbo].[FPI] ([idFPI]),
    CONSTRAINT [FK_bipedestacion_retropie] FOREIGN KEY ([id_retropie]) REFERENCES [dbo].[retropie] ([idRetropie])
);

