CREATE TABLE [dbo].[decubitoSupinoExploracionMuscular] (
    [idEMuscularPieIzdo]            UNIQUEIDENTIFIER NOT NULL,
    [idEMuscularPieDcho]            UNIQUEIDENTIFIER NOT NULL,
    [aductoresCaderaIzdo]           NVARCHAR (MAX)   NULL,
    [aductoresCaderaDcho]           NVARCHAR (MAX)   NULL,
    [cudricepsFemoralIzdo]          NVARCHAR (MAX)   NULL,
    [cudricepsFemoralDcho]          NVARCHAR (MAX)   NULL,
    [isquiotibialesIzdo]            NVARCHAR (MAX)   NULL,
    [isquiotibialesDcho]            NVARCHAR (MAX)   NULL,
    [tibialPosteriorIzdo]           NVARCHAR (MAX)   NULL,
    [tibialPosteriorDcho]           NVARCHAR (MAX)   NULL,
    [flexProp1Izdo]                 NVARCHAR (MAX)   NULL,
    [flexProp1Dcho]                 NVARCHAR (MAX)   NULL,
    [plcYpplIzdo]                   NVARCHAR (MAX)   NULL,
    [plcYpplDcho]                   NVARCHAR (MAX)   NULL,
    [tibialAnterioryExteriorIzdo]   NVARCHAR (MAX)   NULL,
    [tibialAnterioryExteriorDcho]   NVARCHAR (MAX)   NULL,
    [extComunDedosIzdo]             NVARCHAR (MAX)   NULL,
    [extComunDedosDcho]             NVARCHAR (MAX)   NULL,
    [musculosFlexoresDorsalesIzdo]  NVARCHAR (MAX)   NULL,
    [musculosFlexoresDorsalesDcho]  NVARCHAR (MAX)   NULL,
    [musculosFlexoresPlantaresIzdo] NVARCHAR (MAX)   NULL,
    [musculosFlexoresPlantaresDcho] NVARCHAR (MAX)   NULL,
    [musculosPronatoriosIzdo]       NVARCHAR (MAX)   NULL,
    [musculosPronatoriosDcho]       NVARCHAR (MAX)   NULL,
    [musculosSemipronatoriosIzdo]   NVARCHAR (MAX)   NULL,
    [musculosSemipronatoriosDcho]   NVARCHAR (MAX)   NULL,
    [simetriaIzdo]                  BIT              NOT NULL,
    [simetriaDcho]                  BIT              NOT NULL,
    [asimetriaIzdo]                 BIT              NOT NULL,
    [asimetriaDcho]                 BIT              NOT NULL,
    [otrosIzdo]                     NVARCHAR (MAX)   NULL,
    [otrosDcho]                     NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_decubitoSupinoExploracionMuscular] PRIMARY KEY CLUSTERED ([idEMuscularPieIzdo] ASC, [idEMuscularPieDcho] ASC)
);

