CREATE TABLE [dbo].[estudioOrtopodologico] (
    [idEOrtopodologico]     UNIQUEIDENTIFIER NOT NULL,
    [id_dse_articular_izdo] UNIQUEIDENTIFIER NULL,
    [id_dse_articular_dcho] UNIQUEIDENTIFIER NULL,
    [id_dse_muscular_dcho]  UNIQUEIDENTIFIER NULL,
    [id_dse_muscular_izdo]  UNIQUEIDENTIFIER NULL,
    [id_dse_morfologico]    UNIQUEIDENTIFIER NULL,
    [id_dp_articular_dcho]  UNIQUEIDENTIFIER NULL,
    [id_dp_articular_izdo]  UNIQUEIDENTIFIER NULL,
    [id_se_articular_dcho]  UNIQUEIDENTIFIER NULL,
    [id_se_articular_izdo]  UNIQUEIDENTIFIER NULL,
    [id_se_muscular_dcho]   UNIQUEIDENTIFIER NULL,
    [id_se_muscular_izdo]   UNIQUEIDENTIFIER NULL,
    [id_adv_frontal]        UNIQUEIDENTIFIER NULL,
    [id_adv_sagital]        UNIQUEIDENTIFIER NULL,
    [id_deambulacion]       UNIQUEIDENTIFIER NULL,
    [id_bipedestacion]      UNIQUEIDENTIFIER NULL,
    [id_pulsos]             UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_estudioOrtopodologico] PRIMARY KEY CLUSTERED ([idEOrtopodologico] ASC),
    CONSTRAINT [FK_estudioOrtopodologico_bipedestacion] FOREIGN KEY ([id_bipedestacion]) REFERENCES [dbo].[bipedestacion] ([idBipedestacion]),
    CONSTRAINT [FK_estudioOrtopodologico_deambulacion] FOREIGN KEY ([id_deambulacion]) REFERENCES [dbo].[deambulacion] ([idDeambulacion]),
    CONSTRAINT [FK_estudioOrtopodologico_decubitoPronoExploracionArticular] FOREIGN KEY ([id_dp_articular_izdo], [id_dp_articular_dcho]) REFERENCES [dbo].[decubitoPronoExploracionArticular] ([idEArticularPieIzdo], [idEArticularPieDcho]),
    CONSTRAINT [FK_estudioOrtopodologico_decubitoSupinoExploracionArticular] FOREIGN KEY ([id_dse_articular_izdo], [id_dse_articular_dcho]) REFERENCES [dbo].[decubitoSupinoExploracionArticular] ([idEArticularIzdo], [idEArticularDcho]),
    CONSTRAINT [FK_estudioOrtopodologico_decubitoSupinoExploracionMorfologica] FOREIGN KEY ([id_dse_morfologico]) REFERENCES [dbo].[decubitoSupinoExploracionMorfologica] ([idEMorfologica]),
    CONSTRAINT [FK_estudioOrtopodologico_decubitoSupinoExploracionMuscular] FOREIGN KEY ([id_dse_muscular_izdo], [id_dse_muscular_dcho]) REFERENCES [dbo].[decubitoSupinoExploracionMuscular] ([idEMuscularPieIzdo], [idEMuscularPieDcho]),
    CONSTRAINT [FK_estudioOrtopodologico_decubitoSupinoPulsos] FOREIGN KEY ([id_pulsos]) REFERENCES [dbo].[decubitoSupinoPulsos] ([idPulsos]),
    CONSTRAINT [FK_estudioOrtopodologico_sedestacionExploracionArticular] FOREIGN KEY ([id_se_articular_izdo], [id_se_articular_dcho]) REFERENCES [dbo].[sedestacionExploracionArticular] ([idEArticularPieIzdo], [idEArticularPieDcho]),
    CONSTRAINT [FK_estudioOrtopodologico_sedestacionExploracionMuscular] FOREIGN KEY ([id_se_muscular_izdo], [id_se_muscular_dcho]) REFERENCES [dbo].[sedestacionExploracionMuscular] ([idEMuscularPieIzdo], [idEMuscularPieDcho]),
    CONSTRAINT [FK_estudioOrtopodologico_visionFrontal] FOREIGN KEY ([id_adv_frontal]) REFERENCES [dbo].[visionFrontal] ([idFrontal]),
    CONSTRAINT [FK_estudioOrtopodologico_visionSagital] FOREIGN KEY ([id_adv_sagital]) REFERENCES [dbo].[visionSagital] ([idSagital])
);

