//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class anguloFick
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public anguloFick()
        {
            this.visionFrontal = new HashSet<visionFrontal>();
        }
    
        public System.Guid idAngulo { get; set; }
        public Nullable<bool> abierto { get; set; }
        public Nullable<bool> cerrado { get; set; }
        public Nullable<bool> neutro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visionFrontal> visionFrontal { get; set; }
    }
}
