//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class calzadoHabitual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calzadoHabitual()
        {
            this.primeraVisita = new HashSet<primeraVisita>();
        }
    
        public System.Guid idCalzado { get; set; }
        public bool deportivos { get; set; }
        public bool vestir { get; set; }
        public bool sandalias { get; set; }
        public bool botines { get; set; }
        public bool tacones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<primeraVisita> primeraVisita { get; set; }
    }
}
