//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class decubitoPronoExploracionArticular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public decubitoPronoExploracionArticular()
        {
            this.estudioOrtopodologico = new HashSet<estudioOrtopodologico>();
        }
    
        public System.Guid idEArticularPieIzdo { get; set; }
        public System.Guid idEArticularPieDcho { get; set; }
        public Nullable<double> caderaRotInternaIzdo { get; set; }
        public Nullable<double> caderaRotInternaDcho { get; set; }
        public Nullable<double> caderaRotExternaIzdo { get; set; }
        public Nullable<double> caderaRotExternaDcho { get; set; }
        public Nullable<double> torsionFemoralInternaIzdo { get; set; }
        public Nullable<double> torsionFemoralInternaDcho { get; set; }
        public Nullable<double> torsionFemoralExternaIzdo { get; set; }
        public Nullable<double> torsionFemoralExternaDcho { get; set; }
        public Nullable<double> torsionTibialInternaIzdo { get; set; }
        public Nullable<double> torsionTibialInternaDcho { get; set; }
        public Nullable<double> torsionTibialExternaIzdo { get; set; }
        public Nullable<double> torsionTibialExternaDcho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudioOrtopodologico> estudioOrtopodologico { get; set; }
    }
}
