//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class decubitoSupinoExploracionMorfologica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public decubitoSupinoExploracionMorfologica()
        {
            this.estudioOrtopodologico = new HashSet<estudioOrtopodologico>();
        }
    
        public System.Guid idEMorfologica { get; set; }
        public bool antepieTriangular { get; set; }
        public string otros { get; set; }
        public Nullable<System.Guid> id_formula_metatarsal { get; set; }
        public Nullable<System.Guid> id_formula_digital { get; set; }
        public Nullable<System.Guid> id_formula_podal { get; set; }
    
        public virtual formulaDigital formulaDigital { get; set; }
        public virtual formulaMetatarsal formulaMetatarsal { get; set; }
        public virtual formulaPodal formulaPodal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudioOrtopodologico> estudioOrtopodologico { get; set; }
    }
}
