//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnostico
    {
        public System.Guid idDiagnostico { get; set; }
        public string anotaciones { get; set; }
        public Nullable<System.Guid> id_primera_visita { get; set; }
        public Nullable<System.Guid> id_tratamiento { get; set; }
    
        public virtual primeraVisita primeraVisita { get; set; }
        public virtual tratamiento tratamiento { get; set; }
    }
}
