//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FPI()
        {
            this.bipedestacion = new HashSet<bipedestacion>();
        }
    
        public System.Guid idFPI { get; set; }
        public Nullable<int> palpacionEstragaloIzda { get; set; }
        public Nullable<int> palpacionEstragaloDcha { get; set; }
        public Nullable<int> curvaturaMaleolarIzda { get; set; }
        public Nullable<int> curvaturaMaleolarDcha { get; set; }
        public Nullable<int> posicionCalcaneoIzda { get; set; }
        public Nullable<int> posicionCalcaneoDcha { get; set; }
        public Nullable<int> prominenciaArticulacionIzda { get; set; }
        public Nullable<int> prominenciaArticulacionDcha { get; set; }
        public Nullable<int> alturaYcongruenciaIzda { get; set; }
        public Nullable<int> alturaYcongruenciaDcha { get; set; }
        public Nullable<int> abduccionYaduccionIzda { get; set; }
        public Nullable<int> abduccionYaduccionDcha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bipedestacion> bipedestacion { get; set; }
    }
}
