//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialClinico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public historialClinico()
        {
            this.paciente = new HashSet<paciente>();
        }
    
        public System.Guid idHistorialClinico { get; set; }
        public string numeroHistorialClinico { get; set; }
        public Nullable<System.Guid> id_ant_podologicos { get; set; }
        public Nullable<System.Guid> id_ant_patologicos { get; set; }
        public Nullable<System.Guid> id_ant_fisiologicos { get; set; }
        public Nullable<System.Guid> id_ant_familiares { get; set; }
        public Nullable<System.Guid> id_estudio { get; set; }
    
        public virtual antecedentesFamiliares antecedentesFamiliares { get; set; }
        public virtual antecedentesFisiologicos antecedentesFisiologicos { get; set; }
        public virtual antecedentesPatologicos antecedentesPatologicos { get; set; }
        public virtual antecedentesPodologicos antecedentesPodologicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paciente> paciente { get; set; }
    }
}
