//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialSoportePlantar
    {
        public System.Guid idMaterialSoportePlantar { get; set; }
        public bool TAD { get; set; }
        public bool resinas { get; set; }
        public bool EVA { get; set; }
        public bool propileno { get; set; }
        public string componentes { get; set; }
        public string otros { get; set; }
        public Nullable<System.Guid> id_tratamiento { get; set; }
    
        public virtual tratamiento tratamiento { get; set; }
    }
}
