//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class primeraVisita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public primeraVisita()
        {
            this.diagnostico = new HashSet<diagnostico>();
            this.pruebasComplementarias = new HashSet<pruebasComplementarias>();
        }
    
        public System.Guid idPrimeraVisita { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> talla { get; set; }
        public string actividadDeportiva { get; set; }
        public bool diabetes { get; set; }
        public bool alergias { get; set; }
        public string tipoAlergias { get; set; }
        public string motivoPrimeraConsulta { get; set; }
        public bool hayDolor { get; set; }
        public string dolorSitio { get; set; }
        public string dolorTipo { get; set; }
        public Nullable<System.DateTime> fechaPrimeraConsulta { get; set; }
        public Nullable<System.Guid> id_podologo { get; set; }
        public Nullable<System.Guid> id_paciente { get; set; }
        public Nullable<System.Guid> id_historial_clinico { get; set; }
        public Nullable<System.Guid> id_tipo_estudio { get; set; }
        public Nullable<System.Guid> id_estudio_ortopodologico { get; set; }
        public Nullable<System.Guid> id_calzado_habitual { get; set; }
    
        public virtual calzadoHabitual calzadoHabitual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diagnostico> diagnostico { get; set; }
        public virtual estudioOrtopodologico estudioOrtopodologico { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual podologo podologo { get; set; }
        public virtual tipoEstudio tipoEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pruebasComplementarias> pruebasComplementarias { get; set; }
    }
}
