//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodoApp.DB.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class pruebasComplementarias
    {
        public System.Guid idPrueba { get; set; }
        public byte[] pedigrafia { get; set; }
        public byte[] rayosX { get; set; }
        public byte[] analisisSanguineo { get; set; }
        public byte[] cultivo { get; set; }
        public byte[] doppler { get; set; }
        public byte[] ecografia { get; set; }
        public byte[] fotos { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.Guid> id_primera_visita { get; set; }
    
        public virtual primeraVisita primeraVisita { get; set; }
    }
}
